name: Run tests on published event
on:
  release:
    types: [published]

build_and_pub:
  needs: [run_tests]

env:
  LOGIN: ${{ secrets.DOCKER_LOGIN }}
  NAME: ${{ secrets.DOCKER_NAME }}

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
      - name: Telegram notification
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_GROUP }}
          token: ${{ secrets.TELEGRAM_BOT}}
          args: Образ залит в docker hub
