name: Run tests on published event
on:
  push:
    tags:
      - 'l*'

jobs:
  prepub_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverage run tests.py
      - name: Tests report
        run: coverage report
      - name: Telegram notification
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_GROUP }}
          token: ${{ secrets.TELEGRAM_BOT}}
          args: Тесты перед публикацией пройдены

  build_and_pub:
    needs: [ prepub_tests ]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:latest -f Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:latest
      - name: Telegram notification
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_GROUP }}
          token: ${{ secrets.TELEGRAM_BOT}}
          args: Образ залит в docker hub